Ums/Ums.Web.Mvc/Controllers/Admin/CourseController.cs
using System.Web.Mvc;
using Ums.Entities;
using Ums.Framework;
using Ums.Service.Interfaces;
using Ums.Web.Mvc.Filters;
using Ums.Web.Mvc.Helpers;

namespace Ums.Web.Mvc.Controllers
{
    [BasicAuthorization(UserType.Admin)]
    public class CourseController : ControllerBase
    {
        private readonly ICourseService _service;
        private readonly IDepartmentService _departmentService;        
        private readonly IUmsFacade _umsFacade;

        public CourseController(ICourseService service, IDepartmentService departmentService, IUmsFacade umsFacade)
        {
            _service = service;
            _departmentService = departmentService;
            _umsFacade = umsFacade;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_service.GetAll());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(_service.GetById(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Departments = _departmentService.GetAll();            
            return View();
        }
                
        [HttpPost]
        public ActionResult Create(Course model)
        {

            if (ModelState.IsValid && _service.Insert(model))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.Id });
            }
            
            ViewBag.Departments = _departmentService.GetAll();
            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model); 
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Departments = _departmentService.GetAll();
            return View(_service.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Course model)
        {
            if (ModelState.IsValid && _service.Update(model))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.Id });
            }

            ViewBag.Departments = _departmentService.GetAll();
            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model);
            
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(_service.GetById(id));
        }
        
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (ModelState.IsValid && _umsFacade.DeleteCourse(id))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Index");
            }
            
            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(_service.GetById(id));
        }
    }
}

Ums/Ums.Web.Mvc/Controllers/Admin/DepartmentController.cs
using System.Web.Mvc;
using Ums.Entities;
using Ums.Service.Interfaces;
using Ums.Framework;
using Ums.Web.Mvc.Filters;
using Ums.Web.Mvc.Helpers;

namespace Ums.Web.Mvc.Controllers
{
    [BasicAuthorization(UserType.Admin)]
    public class DepartmentController : ControllerBase
    {
        private readonly IDepartmentService _service;
        private readonly IUmsFacade _umsFacade;
        public DepartmentController(IDepartmentService service, IUmsFacade umsFacade)
        {
            _service = service;
            _umsFacade = umsFacade;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_service.GetAll());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(_service.GetById(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
                
        [HttpPost]
        public ActionResult Create(Department model)
        {
            if (ModelState.IsValid && _service.Insert(model))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.Id });
            }

            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(_service.GetById(id));
        }

        [HttpPost]
        public ActionResult Edit(Department model)
        {
            if (ModelState.IsValid && _service.Update(model))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.Id });
            }

            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(_service.GetById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (ModelState.IsValid && _umsFacade.DeleteDepartment(id))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Index");
            }

            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(_service.GetById(id));
        }
    }
}

Ums/Ums.Web.Mvc/Controllers/Admin/RegistrationController.cs
using System.Web.Mvc;
using System.Linq;
using Ums.Entities;
using Ums.Service.Interfaces;
using Ums.Web.Mvc.Helpers;
using Ums.Web.Mvc.Filters;
using Ums.Framework;

namespace Ums.Web.Mvc.Controllers
{
    [BasicAuthorization(UserType.Admin)]
    public class RegistrationController : ControllerBase
    {
        private readonly IRegistrationService _service;
        private readonly IDepartmentService _departmentService;
        private readonly IStudentService _studentService;
        private readonly ISectionService _sectionService;

        public RegistrationController(IRegistrationService service, IDepartmentService departmentService, IStudentService studentService, ISectionService sectionService)
        {
            _service = service;
            _departmentService = departmentService;
            _studentService = studentService;
            _sectionService = sectionService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_departmentService.GetAll());
        }

        [HttpGet]
        public ActionResult Details(int id) //Section ID
        {
            return View(_sectionService.GetById(id));
        }

        [HttpGet]
        public ActionResult Create(int id) //Section ID
        {
            Section section = _sectionService.GetById(id);

            Registration model = new Registration()
            {
                Section = section,
                CourseId = section.CourseId,
                SectionId = id
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Registration model)
        {
            Student student = _studentService.GetByFormattedId(Request["formattedId"]);
            Section section = _sectionService.GetById(model.SectionId);

            if (student != null && section != null)
            {
                model.DateTime = System.DateTime.Now;
                model.StudentId = student.Id;
                if (ModelState.IsValid && student.DepartmentId==section.Course.DepartmentId && _service.Insert(model))
                {
                    TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                    return RedirectToAction("Details", new { id = model.SectionId });
                }
            }            

            model.Section = section;
            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "The Student is already Registered in this section or does not belong to this course");
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)  //Registration ID
        {
            return View(_service.GetById(id));
        }

        [HttpPost]
        public ActionResult Delete(Registration model)
        {
            model = _service.GetById(model.Id);
            if (ModelState.IsValid && _service.Delete(model.Id))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.SectionId });
            }

            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model);
        }
    }
}

Ums/Ums.Web.Mvc/Controllers/Admin/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ums.Entities;
using Ums.Framework;
using Ums.Service.Interfaces;
using Ums.Web.Mvc.Filters;
using Ums.Web.Mvc.Models;

namespace Ums.Web.Mvc.Controllers.Admin
{
    [BasicAuthorization(UserType.Admin)]
    public class ReportController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IDepartmentService _departmentService;

        public ReportController(IDepartmentService departmentService, ICourseService courseService)
        {
            _departmentService = departmentService;
            _courseService = courseService;
        }

        [HttpGet]
        public ActionResult RegistrationsOverview()
        {
            ChartVM barChartVM = new ChartVM();
            IEnumerable<Department> departments = _departmentService.GetAll();

            foreach (var department in departments)
            {
                int count = department.Courses.Sum(x => x.Sections.Sum(y => y.Students.Distinct().Count()));
                //if (count != 0)
                barChartVM.Labels.Add(department.Name);
                barChartVM.Data.Add(count);
            }

            return View(barChartVM);
        }

        [HttpGet]
        public ActionResult RegistrationsByDepartment()
        {
            IEnumerable<Department> departments = _departmentService.GetAll();
            var result = from dept in departments
                         select new RegistrationsByDepartment()
                         {
                             Department = dept.Name,
                             CourseCount = dept.Courses.Count(),
                             SectionCount = dept.Courses.Sum(x => x.Sections.Count()),
                             StudentCount = dept.Courses.Sum(x => x.Sections.Sum(y=>y.Students.Count()))
                         };

            var model = new RegistrationsByDepartmentVM()
            {
                RegistrationsByDepartment = result,
                TotalDepartments = result.Count(),
                TotalCourses = result.Sum(x => x.CourseCount),
                TotalSections = result.Sum(x => x.SectionCount),
                TotalStudents = result.Sum(x => x.StudentCount)
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult RegistrationsByCourse()
        {
            IEnumerable<Course> courses = _courseService.GetAll();
            var result = from course in courses
                         select new RegistrationsByCourse()
                         {
                             Course = String.Format("{0}: {1}", course.Code, course.Name),
                             SectionCount = course.Sections.Count(),
                             StudentCount = course.Sections.Sum(x => x.Students.Count())
                         };

            var model = new RegistrationsByCourseVM()
            {
                RegistrationsByCourse = result,
                TotalCourses = result.Count(),
                TotalSections = result.Sum(x => x.SectionCount),
                TotalStudents = result.Sum(x => x.StudentCount)
            };

            return View(model);
        }
    }
}

Ums/Ums.Web.Mvc/Controllers/Admin/StudentController.cs
using System.Web.Mvc;
using Ums.Entities;
using Ums.Service.Interfaces;
using Ums.Framework;
using Ums.Web.Mvc.Filters;
using Ums.Web.Mvc.Helpers;
using System;
using System.Collections;
using System.Security.Cryptography;

namespace Ums.Web.Mvc.Controllers
{
    [BasicAuthorization(UserType.Admin)]
    public class StudentController : ControllerBase
    {
        private readonly IStudentService _service;
        private readonly IDepartmentService _departmentService;
        private readonly IUmsFacade _umsFacade;
        private readonly CryptoHelper _cryptoHelper;

        public StudentController(IStudentService service, IDepartmentService departmentService, IUmsFacade umsFacade, CryptoHelper cryptoHelper)
        {
            _service = service;
            _departmentService = departmentService;
            _umsFacade = umsFacade;
            _cryptoHelper = cryptoHelper;
        }

        [HttpGet]
        public ActionResult Index()
        {            
            return View(_service.GetAll());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(_service.GetById(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Departments = _departmentService.GetAll();
            return View();
        }
                
        [HttpPost]
        public ActionResult Create(Student model)
        {
            model.Type = UserType.Student;
            using (MD5 md5Hash = MD5.Create())
            {
                model.Password = _cryptoHelper.GetMd5Hash(md5Hash, "0");
            }
            ModelState["Password"].Errors.Clear();          
            int count = ((ICollection)_service.GetAll()).Count;
            model.FormattedId = String.Format($"{DateTime.Now.Year.ToString().Substring(2, 2)}-{model.DepartmentId}-{count}");
            ModelState["FormattedId"].Errors.Clear();

            if (ModelState.IsValid && _service.Insert(model))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.Id });
            }

            ViewBag.Departments = _departmentService.GetAll();
            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Departments = _departmentService.GetAll();
            return View(_service.GetById(id));
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(Student model)
        {
            ModelState["Password"].Errors.Clear();

            if (ModelState.IsValid && _service.Update(model))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Details", new { id = model.Id });
            }

            ViewBag.Departments = _departmentService.GetAll();
            ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(_service.GetById(id));
        }
        
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            if (ModelState.IsValid && _umsFacade.DeleteStudent(id))
            {
                TempData["AlertMessage"] = AlertHelper.SuccessAlert("Success!", "Your last operation was successful");
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.AlertMessage = AlertHelper.DangerAlert("Error!", "Your last operation issued an error");
                return View(_service.GetById(id));
            }
        }
    }
}

Ums/Ums.Web.Mvc/Views/Dashboard/Admin.cshtml
@model AdminDashboardVM
@using Newtonsoft.Json;
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_LayoutPrivate.cshtml";
}

<!-- Content Row -->
<div class="row">

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Departments</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <a href="@Url.Action("Index", "Department")">
                                @Model.DepartmentCount
                            </a>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-file fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Courses</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <a href="@Url.Action("Index", "Course")">
                                @Model.CourseCount
                            </a>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-pen fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Students</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <a href="@Url.Action("Index", "Student")">
                                @Model.StudentCount
                            </a>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-user fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Registrations</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">
                            <a href="@Url.Action("Index", "Registration")">
                                @Model.RegistrationCount
                            </a>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-screwdriver fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Content Row -->

<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">
                    <a href="@Url.Action("RegistrationsOverview", "Report")">
                        Registrations Overview
                    </a>
                </h6>
            </div>
            <div class="card-body">
                <div class="chart-bar">
                    <div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                    <canvas id="myBarChart" width="825" height="320" class="chartjs-render-monitor" style="display: block; width: 825px; height: 320px;"></canvas>
                </div>
            </div>
        </div>
    </div>


    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">
                    <a href="@Url.Action("Index", "User")">
                        Users
                    </a>                    
                </h6>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                    <div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                    <canvas id="myPieChart" style="display: block; width: 551px; height: 208px;" width="551" height="208" class="chartjs-render-monitor"></canvas>
                </div>
                <div class="mt-4 text-center small">
                    <span class="mr-2">
                        <i class="fas fa-circle text-primary"></i> Admin
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-success"></i> Student
                    </span>                    
                </div>
            </div>
        </div>
    </div>
</div>

@section PageLevelScripts{
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <script>
        function populateBarChart(barChartData) {
            //console.log(barChartData);

            var ctx = $("#myBarChart");
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: barChartData.Labels,//['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange', 'Yellow', 'Green', 'Purple', 'Orange'],
                    datasets: [{
                        label: '# of Students',
                        data: barChartData.Data,//[16, 4, 1, 1, 1, 0, 4, 1, 1, 1],
                        backgroundColor: 'rgba(54, 162, 235, 0.2)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    legend: {
                        display: false
                    },
                    maintainAspectRatio: false,
                    layout: {
                        padding: {
                            left: 10,
                            right: 25,
                            top: 25,
                            bottom: 0
                        }
                    },
                    scales: {
                        xAxes: [{                            
                            gridLines: {
                                display: false,
                                drawBorder: false
                            }
                        }],
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            },
                            gridLines: {
                                color: "rgb(234, 236, 244)",
                                zeroLineColor: "rgb(234, 236, 244)",
                                drawBorder: false,
                                borderDash: [2],
                                zeroLineBorderDash: [2]
                            }
                        }]
                    }
                }
            });
        }

        function populatePieChart(pieChartData) {
            var ctx = $("#myPieChart");
            var myPieChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: pieChartData.Labels,//["Direct", "Referral", "Social"],
                    datasets: [{
                        data: pieChartData.Data,//[55, 30, 15],
                        backgroundColor: ['#4e73df', '#1cc88a', '#36b9cc'],
                        hoverBackgroundColor: ['#2e59d9', '#17a673', '#2c9faf'],
                        hoverBorderColor: "rgba(234, 236, 244, 1)",
                    }],
                },
                options: {
                    maintainAspectRatio: false,
                    tooltips: {
                        backgroundColor: "rgb(255,255,255)",
                        bodyFontColor: "#858796",
                        borderColor: '#dddfeb',
                        borderWidth: 1,
                        xPadding: 15,
                        yPadding: 15,
                        displayColors: false,
                        caretPadding: 10,
                    },
                    legend: {
                        display: false
                    },
                    cutoutPercentage: 80,
                },
            });
        }

        populateBarChart(@Html.Raw(JsonConvert.SerializeObject(Model.BarChartVM)));
        populatePieChart(@Html.Raw(JsonConvert.SerializeObject(Model.PieChartVM)));
    </script>
}

Ums/Ums.Web.Mvc/Views/Dashboard/Student.cshtml
@model IEnumerable<Registration>
@{
    ViewBag.Title = "Student";
    Layout = "~/Views/Shared/_LayoutPrivate.cshtml";

    Student student = Session["User"] as Student;
}

<!-- Content Row -->
<div class="row">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Department</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@student.Department.Name</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-user fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">CGPA</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@student.Cgpa</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-screwdriver fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Courses</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.Count()</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-user fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Status</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@(student.IsActive ? "Active" : "Blocked")</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-user fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<h1 class="h3 mt-3 mb-0 text-black-50">Registered Courses</h1>
<hr />

<div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>
                    Course
                </th>
                <th>
                    Section
                </th>
                <th>
                    Credit
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <strong>@item.Section.Course.Code</strong>: @item.Section.Course.Name
                    </td>
                    <td>
                        @item.Section.Name
                    </td>
                    <td>
                        @item.Section.Course.Credit
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>


@section PageLevelStyles{
    <link href="~/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
}

@section PageLevelScripts{
    <script src="~/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function () {
            $('#dataTable').DataTable();
        });
    </script>
}